apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: siddhartha54/bakery-frontend:48  # Replace with your image tag
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
