frontend:
  replicaCount: 4
  image:
    repository: siddhartha54/bakery-frontend
    tag: "48"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    targetPort: 3000
  env:
    REACT_APP_SERVER_DOMAIN: "http://backend.bakery.svc.cluster.local:5000"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

backend:
  replicaCount: 4
  image:
    repository: siddhartha54/bakery-backend
    tag: "48"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  env:
    MONGO_INITDB_ROOT_USERNAME: "prodUser"
    MONGO_INITDB_ROOT_PASSWORD: "prodPass"
    MONGO_DB_NAME: "bakeryProd"
    MONGO_URI: "mongodb://prodUser:prodPass@mongo:27017/bakeryProd"
  resources:
    limits:
      cpu: 700m
      memory: 768Mi
    requests:
      cpu: 400m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

mongo:
  replicaCount: 4
  image:
    repository: mongo
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: bakery.yourdomain.com
      paths:
        - /

nodeSelector: {}
tolerations: []
affinity: {}
