apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: frontend
          image: siddhartha54/bakery-frontend:48  # Replace with your dev image
          
