apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bakery 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: siddhartha54/bakery-frontend:49
          ports:
            - containerPort: 80    
          env:
            - name: REACT_APP_SERVER_DOMIN
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_SERVER_DOMIN
