apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: siddhartha54/bakery-backend:48  # Replace with your image
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
