# mongo-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-user: bW9uZ29hZG1pbg==  # base64 for 'mongoadmin'
  mongo-root-password: c2VjdXJlcGFzcw== # base64 for 'securepass'