name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate a descriptive Image Tag
      id: image_tag
      run: echo "TAG=$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: siddhartha54/bakery-frontend:${{ steps.image_tag.outputs.TAG }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: siddhartha54/bakery-backend:${{ steps.image_tag.outputs.TAG }}

    - name: Save image tag to file for artifact
      run: echo "${{ steps.image_tag.outputs.TAG }}" > image_tag.txt

    - name: Upload image tag as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image_tag.txt
