name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set Unique Image Tag
      id: vars
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build Frontend Image
      run: docker build -t siddhartha54/bakery-frontend:${{ env.IMAGE_TAG }} ./frontend

    - name: Build Backend Image
      run: docker build -t siddhartha54/bakery-backend:${{ env.IMAGE_TAG }} ./backend

    - name: Push Frontend Image
      run: docker push siddhartha54/bakery-frontend:${{ env.IMAGE_TAG }}

    - name: Push Backend Image
      run: docker push siddhartha54/bakery-backend:${{ env.IMAGE_TAG }}

    - name: Save Image Tag
      run: echo "image_tag=${{ env.IMAGE_TAG }}" > image_tag.txt

    - name: Upload image tag
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image_tag.txt
