# deploy.yml
name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  update-deployments:
    runs-on: ubuntu-latest
    # Important: Only run this job if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Grant permissions for the GITHUB_TOKEN to push to the repository
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download image tag artifact
      uses: actions/download-artifact@v4
      with:
        name: image-tag
        # FIX: Specify the ID of the run that created the artifact
        run-id: ${{ github.event.workflow_run.id }}
        path: .

    - name: Load image tag from file
      run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

    - name: Update Kubernetes Deployment YAMLs
      run: |
        sed -i "s|image: .*/bakery-frontend:.*|image: siddhartha54/bakery-frontend:${{ env.IMAGE_TAG }}|" kubernetes/frontend/deployment.yml
        sed -i "s|image: .*/bakery-backend:.*|image: siddhartha54/bakery-backend:${{ env.IMAGE_TAG }}|" kubernetes/backend/deployment.yml

    - name: Commit and Push Updated YAMLs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add kubernetes/frontend/deployment.yml kubernetes/backend/deployment.yml
        # Check if there are changes to commit
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update image tags to ${{ env.IMAGE_TAG }}"
          git push
        else
          echo "No changes to commit."
        fi
