name: CI/CD for Bakery Project

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set Unique Image Tag
      id: vars
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build Frontend Image
      run: docker build -t siddhartha54/bakery-frontend:${{ env.IMAGE_TAG }} ./frontend
      env:
        REACT_APP_SERVER_URL: ""

    - name: Build Backend Image
      run: docker build -t siddhartha54/bakery-backend:${{ env.IMAGE_TAG }} ./backend

    - name: Push Frontend Image
      run: docker push siddhartha54/bakery-frontend:${{ env.IMAGE_TAG }}

    - name: Push Backend Image
      run: docker push siddhartha54/bakery-backend:${{ env.IMAGE_TAG }}

    - name: Update Frontend Deployment
      run: |
        sed -i "s|image: .*/bakery-frontend:.*|image: siddhartha54/bakery-frontend:${{ env.IMAGE_TAG }}|" kubernetes/frontend/deployment.yml

    - name: Update Backend Deployment
      run: |
        sed -i "s|image: .*/bakery-backend:.*|image: siddhartha54/bakery-backend:${{ env.IMAGE_TAG }}|" kubernetes/backend/deployment.yml

    - name: Git Commit & Push Updated YAMLs
      run: |
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git add kubernetes/frontend/deployment.yml kubernetes/backend/deployment.yml
        git commit -m "Update image tags to ${{ env.IMAGE_TAG }}"
        git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
