name: Email Notification on CI/CD Completion

on:
  workflow_run:
    workflows: ["CI/CD for Bakery Project"]
    types:
      - completed

jobs:
  email-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email via Gmail
      if: always()  # Always run, even if workflow failed
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "🚀 CI/CD Completed: ${{ github.workflow }}"
        to: ${{ secrets.EMAIL_TO }}
        from: GitHub Actions <${{ secrets.EMAIL_USER }}>
        content_type: text/html
        body: |
          <h3>✅ CI/CD Workflow Completed</h3>
          <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
          <p><strong>Repository:</strong> ${{ github.repository }}</p>
          <p><strong>Status:</strong> ${{ job.status }}</p>
          <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">🔗 View Full Run</a></p>
